# Generated by Django 2.2 on 2021-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='userlike', to='store_app.User'),
        ),
    ]
