# Generated by Django 2.2 on 2021-06-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_auto_20210602_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
