# Generated by Django 2.2 on 2021-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20210603_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
